import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SiteIntro from "@/components/ui/SiteIntro";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Team Automatons",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
        <SiteIntro enableAudio={false} />
        {children}
      </body>
    </html>
  );
}
